services:

  fastapi:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./db:/db/
    # env_file:
    #   - ../src/config/env/.env
    command:
      - ./entrypoint.sh